name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        pip install pylint hypixel apscheduler requests websocket-client flashtext jieba mcstatus pillow psutil matplotlib simhash selenium
    - name: Analysing the code with pylint
      run: |
        pylint --disable=C,W,R ./main.py
