name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.6"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m ensurepip --default-pip
        python -m pip install --upgrade pip
        pip install pylint hypixel apscheduler requests tcping websocket-client mcstatus pillow psutil matplotlib 
        pip3 install nonebot2
    - name: Analysing the code with pylint
      run: |
        pylint --disable=C,W,R ./main.py
